stages:
  - deploy

variables:
  PROJECT_ID: question-agent-ytt

deploy:
  stage: deploy
  image: google/cloud-sdk:slim
  only:
    - master
  id_tokens:
    GCP_ID_TOKEN:
      aud: https://iam.googleapis.com/projects/999418370792/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
  before_script:
    - echo $GCP_ID_TOKEN > /tmp/id_token.txt
    - gcloud iam workload-identity-pools create-cred-config
        projects/999418370792/locations/global/workloadIdentityPools/gitlab-pool/providers/gitlab-provider
        --service-account=gitlab-ci@question-agent-ytt.iam.gserviceaccount.com
        --output-file=/tmp/creds.json
        --credential-source-file=/tmp/id_token.txt
    - gcloud auth login --cred-file=/tmp/creds.json --quiet
    - apt-get install -y -qq nodejs npm
    - npm install -g npm@latest
    - npm ci
  script:
    - npm run build
    - python3 deploy_hosting.py
  environment:
    name: production
